### ISSUE TITLE
No error maps generated when non-existent save directory is given

### ISSUE THREAD

**Issue by xge** [NVlabs/flip#11]
I stumbled across this very minor nuisance when using flip: 
Specifying an output directory for the error maps using the `-d` parameter, flip fails silently if the directory does not exist. This results in no error maps being saved.

**Example**:
Running `flip-cuda.exe -d output -r reference.png -t test.png` will not create the `output` directory, but instead flip will print the metrics and then exit.

**Expected behavior**:
Either create the directory or print a warning that the error maps will not be saved.

**Comment by inversepixel** [comment]
On it!

**Comment by inversepixel** [comment]
Done!

**Comment by inversepixel** [comment]
Note that if you use \ in your filename you need to use two of them, i.e., `--directory mydir\\subdir`
