### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by nguyeeq1** [NVlabs/flip#19]
Would it be possible to publish the Python implementations of ꟻLIP to PyPI? It would be really convenient to directly pip install the package from command-line.

**Comment by inversepixel** [comment]
Hello there!
Can you give us some hints on how that would be done?
Thanks!

**Comment by nguyeeq1** [comment]
Sure thing! There are numerous guides and tutorials out there, but it would basically involve turning the Python implementation of flip into a package with expected file hierarchy, creating the necessary files for setup (setup.py, setup.cfg, pyproject.toml, license, etc.), then creating an account on PyPi and uploading via command line. Here are a couple links that could be useful:

- https://packaging.python.org/en/latest/tutorials/packaging-projects/
- https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56

Happy to be of more help if wanted!

**Comment by inversepixel** [comment]
With v1.4, you can now write: `pip install -r requirements.txt .`
So, it's a step towards the real `pip install flip`
Hopefully, we can sort that out for v1.5. Closing this comment now.
