### ISSUE TITLE
Installation Guide For Python `venv`

### ISSUE THREAD

**Issue by YTKme** [NVlabs/flip#26]
Hello, I tried to get this repository to work with Python `venv` on macOS. But having issue installing OpenEXR. Is there a method to get this repository working with Python `venv` on macOS?

**Comment by inversepixel** [comment]
Hello! Thanks for writing. We are working towards a solution so that you can install flip using `pip install flip` or something like that. Would that work for you?

**Comment by YTKme** [comment]
> Hello! Thanks for writing. We are working towards a solution so that you can install flip using `pip install flip` or something like that. Would that work for you?

I think that would work great, but not sure if it will be a binary package or wrapper, the issue I encountered with OpenEXR is that the missing libraries could not be compiled correctly on macOS, and dependency for those missing libraries had issue as well. ([cross post here](https://github.com/404Vector/OpenEXR-Python/issues/2#issuecomment-1926316033)).
But yes, having `pip install flip` would be great!

**Comment by inversepixel** [comment]
With v1.4, you can now write: `pip install -r requirements.txt .`
So, it's a step towards the real `pip install flip`
Hopefully, we can sort that out for v1.5. Closing this comment now.

**Comment by YTKme** [comment]
Hi @inversepixel,

Thank you for the update!

I tried this out on my Windows 11 machine and it worked fine with no issues.

But when I tried it on my macOs machine, I am getting an error for `extra_link_args`.

```bash
(pv312-flip) yk 💻 yk 📂 python 🌱 (main|u=)
$ pip install -r requirements.txt .
Processing /Users/yk/Desktop/Project/Repository/YK/flip/python
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/yk/Desktop/Project/Workspace/Python/pv312-flip/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/yk/Desktop/Project/Workspace/Python/pv312-flip/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/yk/Desktop/Project/Workspace/Python/pv312-flip/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/wd/43c5yw956bb870c0wcwwy21h0000gq/T/pip-build-env-pg8kmyyt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/wd/43c5yw956bb870c0wcwwy21h0000gq/T/pip-build-env-pg8kmyyt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/wd/43c5yw956bb870c0wcwwy21h0000gq/T/pip-build-env-pg8kmyyt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/wd/43c5yw956bb870c0wcwwy21h0000gq/T/pip-build-env-pg8kmyyt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 55, in <module>
      NameError: name 'extra_link_args' is not defined. Did you mean: 'extra_compile_args'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(pv312-flip) yk 💻 yk 📂 python 🌱 (main|u=)
```

**Comment by theBoilingPoint** [comment]
> Hi @inversepixel,
> 
> Thank you for the update!
> 
> I tried this out on my Windows 11 machine and it worked fine with no issues.
> 
> But when I tried it on my macOS machine, I am getting an error for `extra_link_args`.
> 
> ```shell
> (pv312-flip) yk 💻 yk 📂 python 🌱 (main|u=)
> $ pip install -r requirements.txt .
> Processing /Users/yk/Desktop/Project/Repository/YK/flip/python
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
> 
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [20 lines of output]
>       Traceback (most recent call last):
>         File "/Users/yk/Desktop/Project/Workspace/Python/pv312-flip/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>           main()
>         File "/Users/yk/Desktop/Project/Workspace/Python/pv312-flip/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/Users/yk/Desktop/Project/Workspace/Python/pv312-flip/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
>           return hook(config_settings)
>                  ^^^^^^^^^^^^^^^^^^^^^
>         File "/private/var/folders/wd/43c5yw956bb870c0wcwwy21h0000gq/T/pip-build-env-pg8kmyyt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=['wheel'])
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/private/var/folders/wd/43c5yw956bb870c0wcwwy21h0000gq/T/pip-build-env-pg8kmyyt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
>           self.run_setup()
>         File "/private/var/folders/wd/43c5yw956bb870c0wcwwy21h0000gq/T/pip-build-env-pg8kmyyt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
>           super().run_setup(setup_script=setup_script)
>         File "/private/var/folders/wd/43c5yw956bb870c0wcwwy21h0000gq/T/pip-build-env-pg8kmyyt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
>           exec(code, locals())
>         File "<string>", line 55, in <module>
>       NameError: name 'extra_link_args' is not defined. Did you mean: 'extra_compile_args'?
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> (pv312-flip) yk 💻 yk 📂 python 🌱 (main|u=)
> ```

Hi, @YTKme !

I have encountered the same issue. Since this issue is closed, I think it would be better to open a new one.

Thank you very much.
