### ISSUE TITLE
Where is pbflip in python wrapper

### ISSUE THREAD

**Issue by R-J96** [NVlabs/flip#28]
Hi, I'm trying to get the python wrapper of this working and everything is fine except that in `flip/python/flip/main.py` the first import of `import pbflip` errors as therre's no module called that available.

This is clearly from pybind11 in `main.cpp`. I've installed pybind with conda and added the directory to `CMakeLists.txt` but it still can't resolve the imports.

Sorry if this is a dumb question but it's not clear from the documentation in the READMEs where this module's supposed to come from

**Comment by pandersson94** [comment]
Hi @R-J96,

Sorry to hear you're having issues with the Python wrapper. Unfortunately, I am not sure exactly what is causing your problem, but I want to help figure it out.

First off, you should not need to install pybind11 yourself. It's done automatically when you run `pip install .` from `flip/python`. Could you try uninstalling your pybind11 version and run `pip install .` again? Furthermore, it could be that things work differently when you do the setup from the Anaconda prompt. I haven't tried doing so -- I've only tested this from the Windows PowerShell and command prompt. Could you try setting things up and running them from any of those? The `pbflip` module should be created automatically when you run `pip install .`.

If neither of the above options help, let us know and we can dig further.

**Comment by michalfratczak** [comment]
Hey - I just had a similar problem where pbflip was not found. In my case it was a typo in installation command.
The command is `pip install -r requirements.txt .` and I accidentaly ommited last period. After reinstalling all works OK.

**Comment by inversepixel** [comment]
Closing since the problem seems to be resolved.
