### ISSUE TITLE
Update instructions of C++ build in README

### ISSUE THREAD

**Issue by comradez** [NVlabs/flip#39]
The building process has been completely overhauled since v1.6 and directly invoking `CMake` now gives a long warning telling the user to use the Python version instead. The `CMakeLists.txt` now triggers `nanobind` to handle the build completely.

Is there still a way to build a standalone C++ binary of FLIP or is it no longer supported after this update? Either way, an update in the README is greatly appreciated.

**Comment by pandersson94** [comment]
Hi @comradez,

Sorry about that. I am looking into it now. Will let you know when there's a fix in place. Thanks for letting us know about the issue!

**Comment by pandersson94** [comment]
@comradez , a fix to the README is now up (see the [changes](https://github.com/NVlabs/flip/commit/cdf09357301d252eaa915ce7aa9f25654fdce86e)).

The way to go about it is exactly the same as before, except for the fact that you need to start from the `src` directory. Sorry we forgot to update the README.

Please let us know if you run into any other issues.

**Comment by comradez** [comment]
Thanks @pandersson94 for the timely reply! Really appreciate that.
